# Generated by Django 2.1.7 on 2023-03-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='useremail',
        ),
    ]
